export enum ActionTypes {
    SET_SEARCH_TEXT = "SET_SEARCH_TEXT",
    SET_SEARCHED_LIST = "SET_SEARCHED_LIST",
    SET_INIT_SEARCHED_LIST = "SET_INIT_SEARCHED_LIST",
    SET_TEMP_SELECTED_ITEMS = "SET_TEMP_SELECTED_ITEMS",
    SET_SELECTED_ITEMS = "SET_SELECTED_ITEMS"
}